<?php
require_once('../includes/auth.php');
require_admin();
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Puntualidad de coordinadores · Estiba</title>
  <link rel="icon" type="image/png" href="../img/logo.jpg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../css/header.css"><link rel="stylesheet" href="../css/sidebar.css"><link rel="stylesheet" href="../css/layout.css"><link rel="stylesheet" href="../css/ui.css"><link rel="stylesheet" href="../css/estiba.css">
  <script src="../js/vendor/xlsx.full.min.js"></script>
  <style>
    .ptr-wrap{--green:#00875a;--deep:#005c3d;--line:rgba(0,135,90,.18);--ink:#1e293b;--mute:#64748b;display:flex;flex-direction:column;gap:18px;font-family:'DM Sans',sans-serif;color:var(--ink)}.ptr-wrap *{box-sizing:border-box}.ptr-hero{padding:25px 28px;border-radius:20px;color:#fff;background:linear-gradient(135deg,var(--deep),var(--green));display:flex;justify-content:space-between;align-items:end;gap:24px}.ptr-kicker{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#9cf0cc}.ptr-hero h1{font-size:25px;letter-spacing:-.02em;margin:5px 0}.ptr-hero p{margin:0;max-width:640px;font-size:13px;color:rgba(255,255,255,.82)}.ptr-window{padding:10px 13px;border:1px solid rgba(255,255,255,.25);border-radius:12px;background:rgba(255,255,255,.12);font-size:12px;white-space:nowrap}.ptr-window b{display:block;font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#b9f5d8;margin-bottom:3px}
    .ptr-filters,.ptr-table-card{border:1px solid var(--line);border-radius:14px;background:#fff}.ptr-filters{display:flex;align-items:end;gap:12px;flex-wrap:wrap;padding:14px}.ptr-field,.ptr-period{display:flex;flex-direction:column;gap:5px}.ptr-period{border-left:1px solid var(--line);padding-left:12px}.ptr-field label,.ptr-label{font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.ptr-field input,.ptr-field select{height:37px;padding:0 10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;font:inherit;font-size:13px;color:var(--ink)}.ptr-field select{min-width:230px}.ptr-btn{height:37px;padding:0 14px;border:1px solid var(--green);border-radius:9px;background:var(--green);color:#fff;font:inherit;font-size:13px;font-weight:700;cursor:pointer}.ptr-btn:hover{background:var(--deep)}.ptr-btn.secondary{margin-left:auto;background:#fff;color:var(--green)}.ptr-month,.ptr-week{height:37px;display:flex;align-items:center;border:1px solid var(--line);border-radius:10px;overflow:hidden}.ptr-month button,.ptr-week button{height:100%;width:34px;border:0;background:#f6fbf9;color:var(--green);font-size:18px;font-weight:800;cursor:pointer}.ptr-month button:hover,.ptr-week button:hover{background:#e5f5ee}.ptr-month span{min-width:150px;text-align:center;font-size:12px;font-weight:800;color:var(--deep)}.ptr-week span{min-width:260px;text-align:center;font-size:11px;font-weight:800;color:var(--deep)}
    .ptr-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.ptr-kpi{border:1px solid var(--line);border-radius:14px;background:#fff;padding:15px 17px}.ptr-kpi span{display:block;font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.ptr-kpi strong{display:block;margin-top:4px;font-size:30px;line-height:1;color:var(--green)}.ptr-kpi.off strong{color:#dc2626}.ptr-kpi.rate strong{color:#1d4ed8}.ptr-kpi.tally strong{color:#7c3aed}.ptr-table-card{overflow:hidden}.ptr-table-head{padding:15px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:12px}.ptr-table-head h2{margin:0;font-size:15px}.ptr-table-head span{font-size:12px;color:var(--mute)}.ptr-table{width:100%;border-collapse:collapse}.ptr-table th{padding:11px 15px;text-align:left;background:#f8fafc;border-bottom:1px solid var(--line);font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.ptr-sort{display:inline-flex;align-items:center;gap:5px;padding:0;border:0;background:transparent;color:inherit;font:inherit;font-weight:inherit;letter-spacing:inherit;text-transform:inherit;cursor:pointer}.ptr-sort:hover{color:var(--deep)}.ptr-sort:focus-visible{outline:2px solid var(--green);outline-offset:3px;border-radius:3px}.ptr-sort-arrow{font-size:14px;line-height:1;color:var(--green)}.ptr-table td{padding:13px 15px;border-bottom:1px solid #edf3f1;font-size:13px}.ptr-table tr:last-child td{border-bottom:0}.ptr-person{font-weight:700}.ptr-sub{display:block;margin-top:2px;font-size:11px;color:var(--mute)}.ptr-time{font-variant-numeric:tabular-nums;font-weight:700}.ptr-badge{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border:1px solid;border-radius:999px;font-size:10px;font-weight:800;letter-spacing:.05em}.ptr-badge:before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor}.ptr-badge.on{background:#dcfce7;border-color:#86efac;color:#15803d}.ptr-badge.off{background:#fef2f2;border-color:#fecaca;color:#dc2626}.ptr-action{padding:7px 10px;border:1px solid #93d9b7;border-radius:8px;background:#fff;color:#047857;font:inherit;font-size:11px;font-weight:800;cursor:pointer}.ptr-action:hover{background:#edf9f2}.ptr-empty{padding:42px 18px;text-align:center;color:var(--mute);font-size:13px}
    .ptr-modal-back{position:fixed;inset:0;z-index:1200;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(15,23,42,.45)}.ptr-modal-back.open{display:flex}.ptr-modal{width:min(900px,100%);max-height:min(78vh,720px);overflow:auto;border-radius:16px;background:#fff;box-shadow:0 18px 60px rgba(15,23,42,.25)}.ptr-modal-head{display:flex;align-items:flex-start;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--line)}.ptr-modal-head h2{font-size:17px;margin:0}.ptr-modal-head p{margin:4px 0 0;font-size:12px;color:var(--mute)}.ptr-modal-close{width:30px;height:30px;border:0;border-radius:8px;background:#f1f5f9;color:#475569;font-size:20px;cursor:pointer}.ptr-modal-table{width:100%;border-collapse:collapse}.ptr-modal-table th,.ptr-modal-table td{padding:12px 16px;text-align:left;border-bottom:1px solid #edf3f1;font-size:12px}.ptr-modal-table th{background:#f8fafc;color:var(--mute);font-size:10px;letter-spacing:.06em;text-transform:uppercase}.ptr-modal-empty{padding:35px;text-align:center;color:var(--mute);font-size:13px}@media(max-width:900px){.ptr-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.content{padding:16px!important}.ptr-hero{align-items:flex-start;flex-direction:column}.ptr-kpis{grid-template-columns:1fr}.ptr-period{border-left:0;padding-left:0;width:100%}.ptr-month,.ptr-week{width:max-content}.ptr-week span{min-width:230px}.ptr-btn.secondary{margin-left:0}.ptr-table-card{overflow:auto}.ptr-table{min-width:820px}.ptr-modal{max-height:85vh}.ptr-modal-table{min-width:680px}}
  </style>
</head>
<body><div class="overlay" id="overlay"></div><div class="shell"><?php $sb_base='..'; include('../includes/sidebar.php'); ?><div class="main-area"><?php include('../includes/header.php'); ?><main class="content"><section class="ptr-wrap">
  <header class="ptr-hero"><div><div class="ptr-kicker">Turno actual · Control de registro</div><h1>Puntualidad y tallys por coordinador</h1><p>Control administrativo de aperturas de turno, tallys registrados y las zonas de asistencia por turno.</p></div><div class="ptr-window"><b>Ventanas válidas</b>Turno día: 06:00–08:00 · Turno noche: 18:00–20:00</div></header>
  <div class="ptr-filters"><div class="ptr-period"><span class="ptr-label">Mes</span><div class="ptr-month"><button type="button" id="ptrPrevMonth" aria-label="Mes anterior">‹</button><span id="ptrMonthLabel">—</span><button type="button" id="ptrNextMonth" aria-label="Mes siguiente">›</button></div></div><div class="ptr-period"><span class="ptr-label">Semana</span><div class="ptr-week"><button type="button" id="ptrPrevWeek" aria-label="Semana anterior">‹</button><span id="ptrWeekLabel">—</span><button type="button" id="ptrNextWeek" aria-label="Semana siguiente">›</button></div></div><div class="ptr-field"><label for="ptrDesde">Desde</label><input id="ptrDesde" type="date"></div><div class="ptr-field"><label for="ptrHasta">Hasta</label><input id="ptrHasta" type="date"></div><div class="ptr-field"><label for="ptrCoord">Coordinador</label><select id="ptrCoord"><option value="">Todos los coordinadores</option></select></div><button class="ptr-btn" id="ptrBuscar">Actualizar reporte</button><button class="ptr-btn secondary" id="ptrClear">Ver todos los registros</button><button class="ptr-btn secondary" id="ptrExport">Exportar Excel</button></div>
  <div class="ptr-kpis"><article class="ptr-kpi"><span>Registros a tiempo</span><strong id="ptrOn">0</strong></article><article class="ptr-kpi off"><span>Registros fuera de tiempo</span><strong id="ptrOff">0</strong></article><article class="ptr-kpi rate"><span>Cumplimiento</span><strong id="ptrRate">—</strong></article><article class="ptr-kpi tally"><span>Tallys registrados</span><strong id="ptrTallyCount">0</strong></article></div>
  <div class="ptr-table-card"><div class="ptr-table-head"><h2>Detalle de registros</h2><span id="ptrCount">Cargando…</span></div><table class="ptr-table"><thead><tr><th>Coordinador</th><th aria-sort="descending"><button type="button" class="ptr-sort" id="ptrOrder" title="Ordenar por fecha y turno"><span>Fecha</span><span class="ptr-sort-arrow" aria-hidden="true">↓</span></button></th><th>Turno</th><th>Hora de registro</th><th>Tallys registrados</th><th>Horas realizadas</th><th>Estado</th><th>Acción</th></tr></thead><tbody id="ptrRows"></tbody></table><div class="ptr-empty" id="ptrEmpty" hidden>No hay registros de turno para los filtros seleccionados.</div></div>
</section></main></div></div>
<div class="ptr-modal-back" id="ptrModalBack" role="dialog" aria-modal="true" aria-labelledby="ptrModalTitle"><div class="ptr-modal"><div class="ptr-modal-head"><div><h2 id="ptrModalTitle">Tallys asignados</h2><p id="ptrModalSub">—</p></div><button type="button" class="ptr-modal-close" id="ptrModalClose" aria-label="Cerrar">×</button></div><div id="ptrModalBody"></div></div></div>
<script>
(() => {const $=id=>document.getElementById(id);let rows=[],tallysPorTurno={},coords=[],monthCursor=new Date(),weekCursor=new Date(),order='desc';const MONTHS=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},short=d=>String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmtHoras=m=>{m=Number(m||0);return Math.floor(m/60)+' h'+(m%60?' '+String(m%60).padStart(2,'0')+' min':'')};
function setRange(a,b){$('ptrDesde').value=iso(a);$('ptrHasta').value=iso(b)}function applyMonth(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('ptrMonthLabel').textContent=MONTHS[m]+' de '+y;setRange(new Date(y,m,1),new Date(y,m+1,0));load()}function weekStart(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const ys=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-ys)/86400000)+1)/7)}function applyWeek(){const a=weekStart(weekCursor),b=new Date(a);b.setDate(a.getDate()+6);$('ptrWeekLabel').textContent='Semana '+isoWeek(a)+' · '+short(a)+' – '+short(b);setRange(a,b);load()}function tallysFor(id){return tallysPorTurno[String(id)]||[]}
 function openTallys(id){const r=rows.find(x=>String(x.id)===String(id));if(!r)return;const list=tallysFor(id);$('ptrModalTitle').textContent='Tallys asignados · '+r.coordinador;$('ptrModalSub').textContent=r.fecha+' · '+r.jornada+' · '+list.length+' tally'+(list.length===1?'':'s')+' registrado'+(list.length===1?'':'s');$('ptrModalBody').innerHTML=list.length?`<table class="ptr-modal-table"><thead><tr><th>Tally</th><th>Código</th><th>Posición</th><th>Zona donde asistió</th><th>Equipo</th><th>Horas realizadas</th></tr></thead><tbody>${list.map(t=>`<tr><td><b>${esc(t.nombre)}</b></td><td>${esc(t.codigo||'—')}</td><td>${esc(t.posicion||t.tipo_funcion||'—')}</td><td>${esc(t.zona||'Sin zona asignada')}</td><td>${esc(t.cuadrilla||'—')}</td><td><b>${fmtHoras(t.minutos_turno)}</b></td></tr>`).join('')}</tbody></table>`:'<div class="ptr-modal-empty">No se registraron tallys vinculados a este coordinador en este turno.</div>';$('ptrModalBack').classList.add('open')}function closeTallys(){$('ptrModalBack').classList.remove('open')}
 function orderedRows(){const direction=order==='desc'?-1:1;return [...rows].sort((a,b)=>{const aKey=a.fecha+(a.jornada_codigo==='N'?'1':'0'),bKey=b.fecha+(b.jornada_codigo==='N'?'1':'0');return aKey===bKey?0:(aKey>bKey?direction:-direction)})}function render(){const on=rows.filter(r=>r.estado_puntualidad==='on').length,off=rows.length-on,total=rows.reduce((s,r)=>s+Number(r.tallys_registrados||0),0),ordered=orderedRows();$('ptrOn').textContent=on;$('ptrOff').textContent=off;$('ptrRate').textContent=rows.length?Math.round(on*100/rows.length)+'%':'—';$('ptrTallyCount').textContent=total;$('ptrCount').textContent=rows.length+' registro'+(rows.length===1?'':'s');$('ptrEmpty').hidden=!!rows.length;$('ptrOrder').setAttribute('aria-label','Ordenar por fecha y turno: '+(order==='desc'?'más reciente primero':'más antiguo primero'));$('ptrOrder').title=$('ptrOrder').getAttribute('aria-label');$('ptrOrder').querySelector('.ptr-sort-arrow').textContent=order==='desc'?'↓':'↑';$('ptrOrder').closest('th').setAttribute('aria-sort',order==='desc'?'descending':'ascending');$('ptrRows').innerHTML=ordered.map(r=>`<tr><td><span class="ptr-person">${esc(r.coordinador)}</span></td><td>${esc(r.fecha)}</td><td><span class="ptr-person">${esc(r.jornada)}</span><span class="ptr-sub">${r.jornada_codigo==='N'?'Noche':'Día'}</span></td><td class="ptr-time">${esc(r.hora_registro)}</td><td><span class="ptr-person">${Number(r.tallys_registrados||0)}</span><span class="ptr-sub">tallys en turno</span></td><td><span class="ptr-person">${fmtHoras(r.minutos_turno)}</span><span class="ptr-sub">del turno registrado</span></td><td><span class="ptr-badge ${r.estado_puntualidad}">${r.estado_puntualidad==='on'?'ON TIME':'OFF TIME'}</span></td><td><button type="button" class="ptr-action" data-turno="${r.id}">Ver tallys y zonas</button></td></tr>`).join('')}
async function load(){const p=new URLSearchParams({desde:$('ptrDesde').value,hasta:$('ptrHasta').value});if($('ptrCoord').value)p.set('coordinador',$('ptrCoord').value);$('ptrCount').textContent='Actualizando…';try{const d=await fetch('../api/get_reporte_puntualidad.php?'+p,{cache:'no-store'}).then(r=>r.json());if(!d.success)throw Error(d.error);const selected=$('ptrCoord').value;coords=d.coordinadores||[];$('ptrCoord').innerHTML='<option value="">Todos los coordinadores</option>'+coords.map(c=>`<option value="${c.id}">${esc(c.nombre)} (${c.tally_count} tallys)</option>`).join('');$('ptrCoord').value=selected;rows=d.registros||[];tallysPorTurno=d.tallys_por_turno||{};render()}catch(e){rows=[];tallysPorTurno={};render();$('ptrCount').textContent=e.message||'No se pudo cargar el reporte'}}
 function exportExcel(){if(!window.XLSX){alert('No se pudo cargar el módulo de Excel.');return}const ordered=orderedRows(),a=[['Coordinador','Fecha','Turno','Hora de registro','Tallys registrados','Horas realizadas','Estado'],...ordered.map(r=>[r.coordinador,r.fecha,r.jornada,r.hora_registro,r.tallys_registrados,fmtHoras(r.minutos_turno),r.estado_puntualidad==='on'?'ON TIME':'OFF TIME'])],b=[['Coordinador','Fecha','Turno','Código','Tally','Posición','Zona donde asistió','Equipo','Horas realizadas'],...ordered.flatMap(r=>tallysFor(r.id).map(t=>[r.coordinador,r.fecha,r.jornada,t.codigo,t.nombre,t.posicion||t.tipo_funcion,t.zona,t.cuadrilla,fmtHoras(t.minutos_turno)]))],book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(a),'Puntualidad');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(b),'Tallys y zonas');XLSX.writeFile(book,'reporte_puntualidad_y_tallys.xlsx')}
 $('ptrPrevMonth').addEventListener('click',()=>{monthCursor.setMonth(monthCursor.getMonth()-1);applyMonth()});$('ptrNextMonth').addEventListener('click',()=>{monthCursor.setMonth(monthCursor.getMonth()+1);applyMonth()});$('ptrPrevWeek').addEventListener('click',()=>{weekCursor.setDate(weekCursor.getDate()-7);applyWeek()});$('ptrNextWeek').addEventListener('click',()=>{weekCursor.setDate(weekCursor.getDate()+7);applyWeek()});$('ptrBuscar').addEventListener('click',load);$('ptrCoord').addEventListener('change',load);$('ptrOrder').addEventListener('click',()=>{order=order==='desc'?'asc':'desc';render()});$('ptrExport').addEventListener('click',exportExcel);$('ptrRows').addEventListener('click',e=>{const b=e.target.closest('[data-turno]');if(b)openTallys(b.dataset.turno)});$('ptrModalClose').addEventListener('click',closeTallys);$('ptrModalBack').addEventListener('click',e=>{if(e.target===$('ptrModalBack'))closeTallys()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTallys()});applyMonth()})();
</script>
<script>
// Restablece el reporte a un rango que incluye todo el historial disponible.
document.getElementById('ptrClear').addEventListener('click', () => {
  document.getElementById('ptrDesde').value = '2000-01-01';
  document.getElementById('ptrHasta').value = '2100-12-31';
  document.getElementById('ptrCoord').value = '';
  document.getElementById('ptrBuscar').click();
});
</script></body></html>
