<?php
require_once('../includes/auth.php');
require_report();
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tardanzas en charlas · Estiba</title>
  <link rel="icon" type="image/png" href="../img/logo.jpg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../css/header.css"><link rel="stylesheet" href="../css/sidebar.css"><link rel="stylesheet" href="../css/layout.css"><link rel="stylesheet" href="../css/ui.css"><link rel="stylesheet" href="../css/estiba.css">
  <script src="../js/vendor/xlsx.full.min.js"></script>
  <style>
    .rtc-wrap{--green:#00875a;--deep:#005c3d;--line:rgba(0,135,90,.18);--ink:#1e293b;--mute:#64748b;display:flex;flex-direction:column;gap:18px;font-family:'DM Sans',sans-serif;color:var(--ink)}.rtc-wrap *{box-sizing:border-box}.rtc-hero{padding:25px 28px;border-radius:20px;color:#fff;background:linear-gradient(135deg,var(--deep),var(--green));display:flex;justify-content:space-between;align-items:end;gap:24px}.rtc-kicker{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#9cf0cc}.rtc-hero h1{font-size:25px;letter-spacing:-.02em;margin:5px 0}.rtc-hero p{margin:0;max-width:640px;font-size:13px;color:rgba(255,255,255,.82)}
    .rtc-filters,.rtc-table-card{border:1px solid var(--line);border-radius:14px;background:#fff}.rtc-filters{display:flex;align-items:end;gap:12px;flex-wrap:wrap;padding:14px}.rtc-field,.rtc-period{display:flex;flex-direction:column;gap:5px}.rtc-period{border-left:1px solid var(--line);padding-left:12px}.rtc-field label,.rtc-label{font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.rtc-field input,.rtc-field select{height:37px;padding:0 10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;font:inherit;font-size:13px;color:var(--ink)}.rtc-search{position:relative}.rtc-search input{padding-left:32px}.rtc-search:before{content:'⌕';position:absolute;left:11px;top:50%;transform:translateY(-50%);font-size:15px;color:#94a3b8}.rtc-btn{height:37px;padding:0 14px;border:1px solid var(--green);border-radius:9px;background:var(--green);color:#fff;font:inherit;font-size:13px;font-weight:700;cursor:pointer}.rtc-btn:hover{background:var(--deep)}.rtc-btn.secondary{margin-left:auto;background:#fff;color:var(--green)}.rtc-month,.rtc-week{height:37px;display:flex;align-items:center;border:1px solid var(--line);border-radius:10px;overflow:hidden}.rtc-month button,.rtc-week button{height:100%;width:34px;border:0;background:#f6fbf9;color:var(--green);font-size:18px;font-weight:800;cursor:pointer}.rtc-month button:hover,.rtc-week button:hover{background:#e5f5ee}.rtc-month span{min-width:150px;text-align:center;font-size:12px;font-weight:800;color:var(--deep)}.rtc-week span{min-width:260px;text-align:center;font-size:11px;font-weight:800;color:var(--deep)}
    .rtc-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rtc-kpi{border:1px solid var(--line);border-radius:14px;background:#fff;padding:15px 17px}.rtc-kpi span{display:block;font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.rtc-kpi strong{display:block;margin-top:4px;font-size:30px;line-height:1;color:var(--green)}.rtc-kpi.off strong{color:#d97706}.rtc-kpi.falta strong{color:#dc2626}.rtc-kpi.charla strong{color:#7c3aed}
    .rtc-tabs{display:flex;gap:8px;padding:14px 14px 0}.rtc-tab{border:1px solid transparent;border-bottom:0;background:transparent;padding:10px 16px;border-radius:10px 10px 0 0;font:inherit;font-size:13px;font-weight:700;color:var(--mute);cursor:pointer;display:flex;align-items:center;gap:8px}.rtc-tab.on{background:#fff;border-color:var(--line);color:var(--green)}.rtc-tab b{background:var(--green);color:#fff;font-size:10px;border-radius:999px;padding:2px 7px}.rtc-tab.on b{background:#dcfce7;color:#15803d}.rtc-table-card{overflow:hidden}.rtc-table-head{padding:15px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:12px}.rtc-table-head h2{margin:0;font-size:15px}.rtc-table-head span{font-size:12px;color:var(--mute)}.rtc-table{width:100%;border-collapse:collapse}.rtc-table th{padding:11px 15px;text-align:left;background:#f8fafc;border-bottom:1px solid var(--line);font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--mute)}.rtc-table td{padding:13px 15px;border-bottom:1px solid #edf3f1;font-size:13px}.rtc-table tr:last-child td{border-bottom:0}.rtc-person{font-weight:700}.rtc-sub{display:block;margin-top:2px;font-size:11px;color:var(--mute)}.rtc-time{font-variant-numeric:tabular-nums;font-weight:700}.rtc-badge{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border:1px solid;border-radius:999px;font-size:10px;font-weight:800;letter-spacing:.05em}.rtc-badge:before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor}.rtc-badge.tardanza{background:#fef3c7;border-color:#fcd34d;color:#b45309}.rtc-badge.asistio{background:#dcfce7;border-color:#86efac;color:#15803d}.rtc-badge.falta{background:#fef2f2;border-color:#fecaca;color:#dc2626}.rtc-count{display:inline-block;min-width:26px;text-align:center;padding:4px 7px;border-radius:8px;font-weight:800;font-size:12px}.rtc-count.tardanza{background:#fef3c7;color:#b45309}.rtc-count.asistio{background:#dcfce7;color:#15803d}.rtc-count.falta{background:#fef2f2;color:#dc2626}.rtc-empty{padding:42px 18px;text-align:center;color:var(--mute);font-size:13px}
    @media(max-width:900px){.rtc-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.content{padding:16px!important}.rtc-hero{align-items:flex-start;flex-direction:column}.rtc-kpis{grid-template-columns:1fr}.rtc-period{border-left:0;padding-left:0;width:100%}.rtc-month,.rtc-week{width:max-content}.rtc-week span{min-width:230px}.rtc-btn.secondary{margin-left:0}.rtc-table-card{overflow:auto}.rtc-table{min-width:780px}}
  </style>
</head>
<body><div class="overlay" id="overlay"></div><div class="shell"><?php $sb_base='..'; include('../includes/sidebar.php'); ?><div class="main-area"><?php include('../includes/header.php'); ?><main class="content"><section class="rtc-wrap">
  <header class="rtc-hero"><div><div class="rtc-kicker">Control de asistencia · Charlas pre-operativas</div><h1>Tardanzas en charlas</h1><p>Cantidad de colaboradores que llegaron tarde a las charlas, con filtro por mes o semana y una vista exclusiva de tardanzas.</p></div></header>
  <div class="rtc-filters"><div class="rtc-period"><span class="rtc-label">Mes</span><div class="rtc-month"><button type="button" id="rtcPrevMonth" aria-label="Mes anterior">‹</button><span id="rtcMonthLabel">—</span><button type="button" id="rtcNextMonth" aria-label="Mes siguiente">›</button></div></div><div class="rtc-period"><span class="rtc-label">Semana</span><div class="rtc-week"><button type="button" id="rtcPrevWeek" aria-label="Semana anterior">‹</button><span id="rtcWeekLabel">—</span><button type="button" id="rtcNextWeek" aria-label="Semana siguiente">›</button></div></div><div class="rtc-field"><label for="rtcDesde">Desde</label><input id="rtcDesde" type="date"></div><div class="rtc-field"><label for="rtcHasta">Hasta</label><input id="rtcHasta" type="date"></div><div class="rtc-field rtc-search"><label for="rtcQ">Buscar colaborador</label><input id="rtcQ" type="text" placeholder="Nombre, DNI o cargo…"></div><button class="rtc-btn" id="rtcBuscar">Actualizar</button><button class="rtc-btn secondary" id="rtcClear">Ver todos</button><button class="rtc-btn secondary" id="rtcExport">Exportar Excel</button></div>
  <div class="rtc-kpis"><article class="rtc-kpi"><span>Colaboradores que llegaron tarde</span><strong id="rtcTard">0</strong></article><article class="rtc-kpi"><span>Asistieron puntual</span><strong id="rtcAsistio">0</strong></article><article class="rtc-kpi falta"><span>Faltaron</span><strong id="rtcFalta">0</strong></article><article class="rtc-kpi charla"><span>Charlas con tardanza</span><strong id="rtcCharlas">0</strong></article></div>
  <div class="rtc-tabs"><button type="button" class="rtc-tab on" id="rtcTabCharlas">Resumen por charla<b id="rtcTabCharlasCount">0</b></button><button type="button" class="rtc-tab" id="rtcTabTardanzas">Solo tardanzas<b id="rtcTabTardanzasCount">0</b></button></div>
  <div class="rtc-table-card">
    <div class="rtc-table-head"><h2 id="rtcTitle">Resumen por charla</h2><span id="rtcCount">Cargando…</span></div>
    <div id="rtcCharlasView"><table class="rtc-table"><thead><tr><th>Fecha</th><th>Charla / tema</th><th>Tipo</th><th>Hora</th><th>Turno</th><th>Coordinador</th><th>Puntual</th><th>Tardanza</th><th>Falta</th><th>Total</th></tr></thead><tbody id="rtcCharlasRows"></tbody></table><div class="rtc-empty" id="rtcCharlasEmpty" hidden>No hay charlas registradas para los filtros seleccionados.</div></div>
    <div id="rtcTardanzasView" hidden><table class="rtc-table"><thead><tr><th>Colaborador</th><th>DNI</th><th>Cargo</th><th>Charla / tema</th><th>Fecha</th><th>Hora</th><th>Turno</th><th>Coordinador</th></tr></thead><tbody id="rtcTardanzasRows"></tbody></table><div class="rtc-empty" id="rtcTardanzasEmpty" hidden>No hay colaboradores con tardanza para los filtros seleccionados.</div></div>
  </div>
</section></main></div></div>
<script>
(() => {const $=id=>document.getElementById(id);let charlas=[],tardanzas=[],kpis={},monthCursor=new Date(),weekCursor=new Date();const MONTHS=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},short=d=>String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TIPOS={charla_seguridad:'Charla de Seguridad',charla_preoperativa:'Charla Pre Operativa'},TURNO={dia:'Día',noche:'Noche',madrugada:'Madrugada'},ETXT=esc('—');
function setRange(a,b){$('rtcDesde').value=iso(a);$('rtcHasta').value=iso(b)}function applyMonth(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('rtcMonthLabel').textContent=MONTHS[m]+' de '+y;setRange(new Date(y,m,1),new Date(y,m+1,0));load()}function weekStart(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const ys=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-ys)/86400000)+1)/7)}function applyWeek(){const a=weekStart(weekCursor),b=new Date(a);b.setDate(a.getDate()+6);$('rtcWeekLabel').textContent='Semana '+isoWeek(a)+' · '+short(a)+' – '+short(b);setRange(a,b);load()}
function renderKpis(){$('rtcTard').textContent=kpis.tardanzas||0;$('rtcAsistio').textContent=kpis.asistio||0;$('rtcFalta').textContent=kpis.falta||0;$('rtcCharlas').textContent=kpis.charlas_con_tardanza||0;$('rtcTabCharlasCount').textContent=charlas.length;$('rtcTabTardanzasCount').textContent=tardanzas.length}
function renderCharlas(){$('rtcTitle').textContent='Resumen por charla';$('rtcCharlasEmpty').hidden=!!charlas.length;$('rtcCharlasRows').innerHTML=charlas.map(c=>`<tr><td>${esc(c.fecha)}</td><td><span class="rtc-person">${esc(c.tema||'—')}</span><span class="rtc-sub">${esc(c.lugar||'')}</span></td><td>${esc(TIPOS[c.tipo_reunion]||c.tipo_reunion||'—')}</td><td class="rtc-time">${esc(c.hora||'—')}</td><td>${esc(TURNO[c.turno]||c.turno||'—')}</td><td>${esc(c.coordinador||'—')}</td><td><span class="rtc-count asistio">${c.asistio}</span></td><td><span class="rtc-count tardanza">${c.tardanzas}</span></td><td><span class="rtc-count falta">${c.faltas}</span></td><td><b>${c.total}</b></td></tr>`).join('')}
function renderTardanzas(){$('rtcTitle').textContent='Solo colaboradores con tardanza';$('rtcTardanzasEmpty').hidden=!!tardanzas.length;$('rtcTardanzasRows').innerHTML=tardanzas.map(t=>`<tr><td><span class="rtc-person">${esc(t.colaborador_nombre||'—')}</span><span class="rtc-badge tardanza">Tardanza</span></td><td>${esc(t.colaborador_dni||'—')}</td><td>${esc(t.colaborador_cargo||'—')}</td><td>${esc(t.tema||'—')}<span class="rtc-sub">${esc(TIPOS[t.tipo_reunion]||t.tipo_reunion||'')}</span></td><td>${esc(t.fecha)}</td><td class="rtc-time">${esc(t.hora||'—')}</td><td>${esc(TURNO[t.turno]||t.turno||'—')}</td><td>${esc(t.coordinador||'—')}</td></tr>`).join('')}
function render(){$('rtcCount').textContent=(charlas.length||0)+' charla'+(charlas.length===1?'':'s')+' · '+(tardanzas.length||0)+' tardanza'+(tardanzas.length===1?'':'s');renderKpis();renderCharlas();renderTardanzas()}
function setView(v){const onCh=v==='charlas';$('rtcTabCharlas').classList.toggle('on',onCh);$('rtcTabTardanzas').classList.toggle('on',!onCh);$('rtcCharlasView').hidden=!onCh;$('rtcTardanzasView').hidden=onCh;render()}
async function load(){const p=new URLSearchParams({desde:$('rtcDesde').value,hasta:$('rtcHasta').value});const q=$('rtcQ').value.trim();if(q)p.set('q',q);$('rtcCount').textContent='Actualizando…';try{const d=await fetch('../api/get_reporte_tardanzas_charlas.php?'+p,{cache:'no-store'}).then(r=>r.json());if(!d.success)throw Error(d.error);charlas=d.charlas||[];tardanzas=d.tardanzas||[];kpis=d.kpis||{};render()}catch(e){charlas=[];tardanzas=[];kpis={};render();$('rtcCount').textContent=e.message||'No se pudo cargar el reporte'}}
function exportExcel(){if(!window.XLSX){alert('No se pudo cargar el módulo de Excel.');return}const a=[['Fecha','Tema','Tipo','Hora','Turno','Coordinador','Puntual','Tardanza','Falta','Total'],...charlas.map(c=>[c.fecha,c.tema,TIPOS[c.tipo_reunion]||c.tipo_reunion,c.hora,TURNO[c.turno]||c.turno,c.coordinador,c.asistio,c.tardanzas,c.faltas,c.total])],b=[['Colaborador','DNI','Cargo','Charla','Fecha','Hora','Turno','Coordinador'],...tardanzas.map(t=>[t.colaborador_nombre,t.colaborador_dni,t.colaborador_cargo,t.tema,t.fecha,t.hora,TURNO[t.turno]||t.turno,t.coordinador])],book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(a),'Resumen por charla');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(b),'Solo tardanzas');XLSX.writeFile(book,'reporte_tardanzas_charlas.xlsx')}
$('rtcPrevMonth').addEventListener('click',()=>{monthCursor.setMonth(monthCursor.getMonth()-1);applyMonth()});$('rtcNextMonth').addEventListener('click',()=>{monthCursor.setMonth(monthCursor.getMonth()+1);applyMonth()});$('rtcPrevWeek').addEventListener('click',()=>{weekCursor.setDate(weekCursor.getDate()-7);applyWeek()});$('rtcNextWeek').addEventListener('click',()=>{weekCursor.setDate(weekCursor.getDate()+7);applyWeek()});$('rtcBuscar').addEventListener('click',load);$('rtcQ').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('rtcClear').addEventListener('click',()=>{$('rtcQ').value='';load()});$('rtcExport').addEventListener('click',exportExcel);$('rtcTabCharlas').addEventListener('click',()=>setView('charlas'));$('rtcTabTardanzas').addEventListener('click',()=>setView('tardanzas'));setView('charlas');applyMonth()})();
</script></body></html>
